import { describe, expect, it, vi, afterEach } from 'vitest';
import { db } from '@/lib/db';
import { smsProvider } from '@/modules/otp/sms-provider';
import {
  isPhoneVerified,
  purgeExpiredOtpRequests,
  requestOtp,
  verifyOtp,
} from '@/modules/otp/otp.service';
import { OtpInvalidError } from '@/modules/otp/otp.errors';
import { RateLimitedError } from '@/lib/errors';

/**
 * Captures the real code otp.service generated by spying on the SMS
 * provider's send call — AGENTS.md §3 rule 8 forbids any app-facing path
 * that echoes the code, so this is the only legitimate way to test the
 * full hash→compare→verify loop (same idea as spying on an EmailProvider
 * to test email content without a real inbox).
 */
async function requestAndCaptureCode(phone: string): Promise<string> {
  const spy = vi.spyOn(smsProvider, 'sendOtp');
  await requestOtp({ phone, purpose: 'cod_confirmation' }, null);
  const call = spy.mock.calls.at(-1);
  spy.mockRestore();
  return call![0].code;
}

function randomPhone(): string {
  return `9${Math.floor(100000000 + Math.random() * 899999999)}`;
}

afterEach(async () => {
  await db.otpRequest.deleteMany({ where: { phone: { startsWith: '9' } } });
});

describe('otp.service.requestOtp / verifyOtp', () => {
  it('sends a 6-digit code and a correct verify succeeds', async () => {
    const phone = randomPhone();
    const code = await requestAndCaptureCode(phone);
    expect(code).toMatch(/^\d{6}$/);

    const verified = await verifyOtp({ phone, code });
    expect(verified.verified).toBe(true);
    expect(verified.verificationId).toBeTruthy();

    const isVerified = await isPhoneVerified(verified.verificationId, phone);
    expect(isVerified).toBe(true);
  });

  it('rejects an incorrect code and counts the attempt', async () => {
    const phone = randomPhone();
    await requestAndCaptureCode(phone);

    await expect(verifyOtp({ phone, code: '000000' })).rejects.toThrow(OtpInvalidError);

    const row = await db.otpRequest.findFirstOrThrow({
      where: { phone },
      orderBy: { createdAt: 'desc' },
    });
    expect(row.attempts).toBe(1);
    expect(row.verified).toBe(false);
  });

  it('permanently fails after max_attempts incorrect guesses', async () => {
    const phone = randomPhone();
    await requestAndCaptureCode(phone);

    for (let i = 0; i < 5; i++) {
      await expect(verifyOtp({ phone, code: '000000' })).rejects.toThrow(OtpInvalidError);
    }
    // A 6th attempt, even if it happened to guess right, must still fail —
    // max_attempts (5) was already exhausted above.
    const row = await db.otpRequest.findFirstOrThrow({
      where: { phone },
      orderBy: { createdAt: 'desc' },
    });
    expect(row.attempts).toBe(5);
  });

  it('rejects an expired code', async () => {
    const phone = randomPhone();
    const code = await requestAndCaptureCode(phone);
    await db.otpRequest.updateMany({
      where: { phone },
      data: { expiresAt: new Date(Date.now() - 1000) },
    });

    await expect(verifyOtp({ phone, code })).rejects.toThrow(OtpInvalidError);
  });

  it('re-verifying an already-verified code is idempotent', async () => {
    const phone = randomPhone();
    const code = await requestAndCaptureCode(phone);
    const first = await verifyOtp({ phone, code });
    const second = await verifyOtp({ phone, code });
    expect(second.verificationId).toBe(first.verificationId);
  });

  it('enforces the 60s resend cooldown', async () => {
    const phone = randomPhone();
    await requestAndCaptureCode(phone);
    await expect(requestOtp({ phone, purpose: 'cod_confirmation' }, null)).rejects.toThrow(
      RateLimitedError,
    );
  });

  it('rate-limits after 3 requests in the 10-minute window', async () => {
    const phone = randomPhone();
    // Seed 3 prior requests directly (bypassing the cooldown, which would
    // otherwise block a 2nd real call before we can reach the count limit).
    for (let i = 0; i < 3; i++) {
      await db.otpRequest.create({
        data: {
          phone,
          purpose: 'cod_confirmation',
          codeHash: 'irrelevant:irrelevant',
          expiresAt: new Date(Date.now() + 300_000),
        },
      });
    }
    await expect(requestOtp({ phone, purpose: 'cod_confirmation' }, null)).rejects.toThrow(
      RateLimitedError,
    );
  });

  it('isPhoneVerified is false for a mismatched phone', async () => {
    const phone = randomPhone();
    const code = await requestAndCaptureCode(phone);
    const verified = await verifyOtp({ phone, code });
    expect(await isPhoneVerified(verified.verificationId, randomPhone())).toBe(false);
  });
});

describe('otp.service.purgeExpiredOtpRequests', () => {
  it('deletes rows older than 24h and leaves recent ones', async () => {
    const oldPhone = randomPhone();
    const recentPhone = randomPhone();
    await db.otpRequest.create({
      data: {
        phone: oldPhone,
        purpose: 'cod_confirmation',
        codeHash: 'x:x',
        expiresAt: new Date(),
        createdAt: new Date(Date.now() - 25 * 60 * 60 * 1000),
      },
    });
    await db.otpRequest.create({
      data: {
        phone: recentPhone,
        purpose: 'cod_confirmation',
        codeHash: 'x:x',
        expiresAt: new Date(),
      },
    });

    const purged = await purgeExpiredOtpRequests();
    expect(purged).toBeGreaterThanOrEqual(1);
    expect(await db.otpRequest.findFirst({ where: { phone: oldPhone } })).toBeNull();
    expect(await db.otpRequest.findFirst({ where: { phone: recentPhone } })).not.toBeNull();
  });
});
