import { toRupeeDisplay } from '@/lib/money';
import { orderStatusLabel } from '@/lib/order-status-display';
import type { NotificationTrigger } from '@/modules/jobs/job.types';
import type { OrderStatus } from '@/modules/orders/order.types';

export interface TemplateContext {
  userName: string;
  orderNumber?: string;
  grandTotal?: number;
}

const ORDER_STATUS_BY_TRIGGER: Partial<Record<NotificationTrigger, OrderStatus>> = {
  order_confirmed: 'confirmed',
  order_processing: 'processing',
  order_packed: 'packed',
  order_shipped: 'shipped',
  order_out_for_delivery: 'out_for_delivery',
  order_delivered: 'delivered',
  order_cancelled: 'cancelled',
};

/**
 * docs/Product_Spec_Requirements.md §10.1's trigger list, minus "email
 * verification"/"password reset" (Firebase sends those natively — never
 * routed through this system) and "invoice attached" (folded into
 * order_confirmed's body as a link to the order page, not a real MIME
 * attachment — the invoice is generated by a separate job that may not
 * have finished yet by the time this one sends; linking to
 * `GET /orders/:id/invoice` avoids that ordering dependency entirely).
 * One function serves both email (html-ish body) and push (title/body) —
 * templates are intentionally plain text/minimal HTML, not a templating
 * engine, since AGENTS.md's anti-overengineering stance applies here too.
 */
export function buildNotificationContent(
  trigger: NotificationTrigger,
  ctx: TemplateContext,
): { title: string; body: string } {
  const order = ctx.orderNumber ?? 'your order';
  const total = ctx.grandTotal !== undefined ? toRupeeDisplay(ctx.grandTotal) : undefined;

  switch (trigger) {
    case 'welcome':
      return {
        title: `Welcome to GreenGrandMart, ${ctx.userName}!`,
        body: `Thanks for creating an account. Start exploring our latest collection.`,
      };
    case 'order_confirmed':
      return {
        title: `Order ${order} confirmed`,
        body: `Your payment was received and order ${order}${total ? ` (${total})` : ''} is confirmed. Your invoice is available on the order page.`,
      };
    case 'payment_failed':
      return {
        title: `Payment failed for order ${order}`,
        body: `We couldn't process payment for order ${order}. You can retry payment from your order page.`,
      };
    case 'order_cancelled':
      return {
        title: `Order ${order} cancelled`,
        body: `Order ${order} has been cancelled.`,
      };
    case 'return_requested':
      return {
        title: `Return requested for order ${order}`,
        body: `We've received your return request for order ${order}. We'll notify you once it's reviewed.`,
      };
    case 'return_approved':
      return {
        title: `Return approved for order ${order}`,
        body: `Your return for order ${order} has been approved. Please ship the item back per the instructions provided.`,
      };
    case 'refund_initiated':
      return {
        title: `Refund initiated for order ${order}`,
        body: `A refund for order ${order} has been initiated and is being processed.`,
      };
    case 'refund_completed':
      return {
        title: `Refund completed for order ${order}`,
        body: `Your refund for order ${order} has been completed.`,
      };
    default: {
      const status = ORDER_STATUS_BY_TRIGGER[trigger];
      const label = status ? orderStatusLabel(status) : trigger;
      return {
        title: `Order ${order}: ${label}`,
        body: `Your order ${order} status is now "${label}".`,
      };
    }
  }
}
